import type { PostEngagementWithContext, FeedbackLoopOutput } from "@/types";

export const feedbackEngagementFixture: PostEngagementWithContext[] = [
  // High performers — Build in Public on LinkedIn
  {
    contentId: "c1",
    platform: "linkedin",
    pillar: "Build in Public",
    title: "How we got our first 100 users",
    likes: 142,
    comments: 38,
    shares: 24,
    reach: 4200,
    impressions: 5800,
    engagementRate: 4.86,
    scheduledFor: new Date("2026-04-01T09:00:00Z"),
  },
  {
    contentId: "c2",
    platform: "linkedin",
    pillar: "Build in Public",
    title: "Revenue milestone: $1k MRR",
    likes: 98,
    comments: 27,
    shares: 15,
    reach: 3100,
    impressions: 4200,
    engagementRate: 4.52,
    scheduledFor: new Date("2026-04-08T09:00:00Z"),
  },
  // Medium performer — Audience Growth on Twitter
  {
    contentId: "c3",
    platform: "twitter",
    pillar: "Audience Growth",
    title: "5 tactics to grow your pre-launch list",
    likes: 64,
    comments: 12,
    shares: 18,
    reach: 2800,
    impressions: 3600,
    engagementRate: 3.36,
    scheduledFor: new Date("2026-04-03T14:00:00Z"),
  },
  {
    contentId: "c4",
    platform: "twitter",
    pillar: "Build in Public",
    title: "Week 8 update: what I shipped",
    likes: 55,
    comments: 9,
    shares: 11,
    reach: 2400,
    impressions: 3100,
    engagementRate: 3.13,
    scheduledFor: new Date("2026-04-10T14:00:00Z"),
  },
  // Medium-low performers
  {
    contentId: "c5",
    platform: "instagram",
    pillar: "Product Marketing",
    title: "Feature sneak peek carousel",
    likes: 45,
    comments: 6,
    shares: 3,
    reach: 1800,
    impressions: 2500,
    engagementRate: 2.16,
    scheduledFor: new Date("2026-04-05T12:00:00Z"),
  },
  {
    contentId: "c6",
    platform: "twitter",
    pillar: "Founder Mindset",
    title: "Why I almost quit last month",
    likes: 38,
    comments: 14,
    shares: 5,
    reach: 1900,
    impressions: 2600,
    engagementRate: 2.19,
    scheduledFor: new Date("2026-04-12T16:00:00Z"),
  },
  // Low performers — Product Marketing on Instagram
  {
    contentId: "c7",
    platform: "instagram",
    pillar: "Product Marketing",
    title: "Product comparison infographic",
    likes: 18,
    comments: 2,
    shares: 1,
    reach: 900,
    impressions: 1400,
    engagementRate: 1.5,
    scheduledFor: new Date("2026-04-07T18:00:00Z"),
  },
  {
    contentId: "c8",
    platform: "instagram",
    pillar: "Audience Growth",
    title: "Community building tips",
    likes: 22,
    comments: 3,
    shares: 2,
    reach: 1100,
    impressions: 1600,
    engagementRate: 1.69,
    scheduledFor: new Date("2026-04-14T11:00:00Z"),
  },
  // Lowest performers
  {
    contentId: "c9",
    platform: "instagram",
    pillar: "Founder Mindset",
    title: "Monday motivation quote",
    likes: 12,
    comments: 1,
    shares: 0,
    reach: 600,
    impressions: 1000,
    engagementRate: 1.3,
    scheduledFor: new Date("2026-04-15T08:00:00Z"),
  },
  {
    contentId: "c10",
    platform: "twitter",
    pillar: "Product Marketing",
    title: "New pricing page is live",
    likes: 8,
    comments: 2,
    shares: 1,
    reach: 700,
    impressions: 1100,
    engagementRate: 1.0,
    scheduledFor: new Date("2026-04-16T20:00:00Z"),
  },
];

export const feedbackOutputFixture: FeedbackLoopOutput = {
  changes: [
    {
      field: "contentPillars",
      oldValue: [
        {
          name: "Build in Public",
          percentage: 35,
          description:
            "Share the journey transparently to build trust and loyalty",
        },
        {
          name: "Audience Growth",
          percentage: 30,
          description: "Tactical community-building tips and strategies",
        },
        {
          name: "Product Marketing",
          percentage: 20,
          description: "Pre-launch strategies, playbooks, and case studies",
        },
        {
          name: "Founder Mindset",
          percentage: 15,
          description: "Resilience, discipline, and motivation for the journey",
        },
      ],
      newValue: [
        {
          name: "Build in Public",
          percentage: 45,
          description:
            "Share the journey transparently to build trust and loyalty",
        },
        {
          name: "Audience Growth",
          percentage: 25,
          description: "Tactical community-building tips and strategies",
        },
        {
          name: "Product Marketing",
          percentage: 15,
          description: "Pre-launch strategies, playbooks, and case studies",
        },
        {
          name: "Founder Mindset",
          percentage: 15,
          description: "Resilience, discipline, and motivation for the journey",
        },
      ],
      reason:
        "Build in Public posts average 4.17% engagement rate vs 1.62% for Product Marketing. Increasing Build in Public allocation from 35% to 45% and reducing Product Marketing from 20% to 15% aligns content strategy with audience preferences.",
    },
    {
      field: "keywords",
      oldValue: [
        "pre-launch marketing",
        "community building",
        "audience building",
        "content strategy",
        "startup marketing",
        "launch strategy",
        "social media automation",
        "founder marketing",
        "build in public",
        "indie hacker",
        "SaaS marketing",
        "content calendar",
      ],
      newValue: [
        "pre-launch marketing",
        "community building",
        "audience building",
        "content strategy",
        "startup marketing",
        "launch strategy",
        "social media automation",
        "founder marketing",
        "build in public",
        "indie hacker",
        "SaaS marketing",
        "content calendar",
        "MRR milestones",
        "founder journey",
      ],
      reason:
        "Top-performing posts reference revenue milestones and transparent founder narratives. Adding 'MRR milestones' and 'founder journey' keywords captures themes that drive 4.5x more engagement than average.",
    },
  ],
  summary:
    "LinkedIn Build in Public content significantly outperforms all other combinations with a 4.69% average engagement rate. Instagram content consistently underperforms across all pillars (avg 1.66%). Recommend shifting content allocation toward Build in Public and deprioritizing Product Marketing on Instagram.",
  confidence: 0.72,
};
